- hosts: kube-master
  tasks:
    - name: Prepare jobs file
      template:
        src: "kube-jobs/{{item}}.j2"
        dest: "{{ansible_user_dir}}/{{item}}.yaml"
      with_items:
        - w-test-sysb-prep-job
        - w-test-sysb-seqwr-job
        - w-test-sysb-rndwr-job
        - r-test-sysb-seqrd-job
        - r-test-sysb-rndrd-job
        - r-test-dd-seqrd-job
        - r-test-ioping-rndrd-job
    # - name: Create /root/.docker dir
    #   become: yes
    #   file:
    #     path: /root/.docker
    #     state: directory
    # - name: Copy json.config
    #   become: yes
    #   copy:
    #     src: config.json
    #     dest: /root/.docker/config.json
    - name: Add public keys
      authorized_key:
        user: "{{ansible_env.USER}}"
        key: "{{ lookup('file', 'pubkeys') }}"

      
